spring:
  profiles:
    active: 
    - test
---
server:
  port: 7001
  
spring:
  profiles: test

eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
---
spring:
  profiles: dev